ALTER TABLE `XIMA_PRD`.`PRD_PRODUCT` DROP INDEX `UX_AlBUM_ID`, ADD UNIQUE `UX_AlBUM_ID` USING BTREE (ALBUM_ID, PRICE_TYPE_ID, BUSINESS_UNIT_ID);

ALTER TABLE `XIMA_PRD`.`PRD_PRODUCT` ADD COLUMN `BUSINESS_UNIT_ID` int(11) DEFAULT '1' AFTER `PRICE_TYPE_ID`;